language: scala
scala:
  - 3.0.1
  - 2.12.8
  - 2.12.1

jdk:
  openjdk11

install:
  - curl -L https://github.com/com-lihaoyi/mill/releases/download/0.9.9/0.9.9 > mill && chmod +x mill
  - curl -fLo https://git.io/coursier-cli && chmod +x coursier && ./coursier && \
    cs install scala3-compiler

script:
  - ./mill eWarehouse[$TRAVIS_SCALA_VERSION].test