language: scala
scala:
  - 3.0.1
  - 2.13.6

jdk:
  openjdk11

install:
  - curl -L https://github.com/com-lihaoyi/mill/releases/download/0.9.9/0.9.9 > mill && chmod +x mill
  - if [[$TRAVIS_SCALA_VERSION == "3.0"]]; then
      curl -fLo coursier https://git.io/coursier-cli &&
      chmod +x coursier &&
      ./coursier install scala3-compiler;
    fi
  - if [[$TRAVIS_SCALA_VERSION == "2.13.6"]]; then
      sdk install scala 2.13.6;
    fi

script:
  - ./mill eWarehouse[$TRAVIS_SCALA_VERSION].test