# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run: curl -fLo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier install scala3-compiler

      - run: curl -L https://github.com/com-lihaoyi/mill/releases/download/0.9.9/0.9.9 > mill && chmod +x mill

      # run tests!
      - run: ./mill eWarehouse[3.0.1].test