name: automated-update
on: [push]
jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: auth
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  authentication:
    runs-on: ubuntu-latest
    steps:
      - name: authentication
        run: |
          cat /home/antonio/token.txt | docker login ghcr.io -u antobalbis --password-stdin
