name: automated-update
on: [push]
jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: auth
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u antobalbis --password-stdin
