name: automated-update
on: [push]
jobs:
  authentication:
    runs-on: ubuntu-latest
    steps:
      - name: authentication
      - run: |
          cat token.txt | docker login ghcr.io -u antobalbis --password-stdin
