name: autoupdate
on: [push]

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: comprobar-repositorio
      uses: actions/checkout@v2

    - name: log in en container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: push-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/antobalbis/easywarehouse:latest

    - name: run image
      run: docker run -t ghcr.io/antobalbis/easywarehouse

  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: comprobar repositorio
        uses: actions/checkout@v2

      - name: iniciar sesión en docker github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build imagen y push a docker github
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: antobalbis/easywarehouse:latest

      - name: run image
        run: docker run -t antobalbis/easywarehouse
