name: automated-docker-update
on: [push]

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-later
    steps:
      - name: comprobar repositorio
        uses: action/checkout@v2

      - name: iniciar sesión en docker github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

        - name: build imagen y push a docker github
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/${{github.repository}}:latest
