name: automated-docker-update
on: [push]

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: comprobar repositorio
        uses: actions/checkout@v2

      - name: iniciar sesión en docker github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build imagen y push a docker github
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: antobalbis/easywarehouse:latest
