name: generate token
on:
  push:
    paths:
      - ".github/workflows/gentoken.yml"

jobs:
  gen-token:
    runs-on: ubuntu-latest
    steps:
      - name: auth
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
